### ISSUE TITLE
Error Message Stays on top of All Screens

### ISSUE THREAD

**Issue by Epigenetic** [LukeEmmet/GemiNaut#30]
The error bubble that appears when there was an error loading a page stays on top of everything, including other windows. If you bring another window on top of GemiNaut, the error will still appear.

![image](https://user-images.githubusercontent.com/9423342/130338931-412d421e-860e-4e70-a3eb-7d6a48749b1f.png)

**Comment by LukeEmmet** [comment]
thanks for the feedback. It should only stay visible if you mouse over it or click it. Otherwise these toast notifications will (or should) auto-close.

I'm using a 3rd party library for these notifications - https://github.com/rafallopatka/ToastNotifications

I dont think it has any options to control this aspect of visibility. So I'm closing this ticket for now, but if you can see a way it can be fixed, please feel free to re-open or submit a pull request. Thanks

**Comment by Epigenetic** [comment]
I wasn't able to get the build working, so instead of futzing around more, based on the documentation their is a cfg.DisplayOptions.TopMost value which can be set to false. I wasn't able to confirm that was what was needed, but it looks like it would be the option desired here.
