### ISSUE TITLE
Program triggers Windows Defender antivirus

### ISSUE THREAD

**Issue by Cycloneblaze** [LukeEmmet/GemiNaut#7]
Like, a lot.

This might be remedied by signing the executable, if that's possible.

**Comment by ffuentese** [comment]
Got the same error. It's the only gemini client that's compiled so I'd love to be able to just download it and go.

**Comment by Dr-WaSaBi** [comment]
Also got the same warning/error...

So I tried to do the download source route, but doesn't seem to be any instructions on how to build it.  So I was winging it.  But looks like needs net framework 4.6, so need to get that I guess.  Maybe opening a new issue about build instructions and seeing if I could help write those might be in order?

**Comment by LukeEmmet** [comment]
Hi everyone - thanks for your input on this issue. I am aware of it and as frustrated as you all are about this. Needless to say it is a false positive.

I'm currently working on a new release which will have an installer, and moreover I'm setting myself up to be able to sign the executable and installer. Hopefully that will result in fewer false positives from AV.

**Comment by LukeEmmet** [comment]
@Dr-WaSaBi - it should be fairly straightforward. Clone the project then open the VS solution file in Visual studio and build the "Release" build. It will create an exe in the bin/release folder. If you can confirm or otherwise whether that works I'd be pleased to hear your feedback.

**Comment by Dr-WaSaBi** [comment]
@LukeEmmet yeah I would if I had visual studio, but I was trying to build it under dotnet core since my data plan only gets me 10 gig a month in hotspot data. So full vs is a bit much for me.  I might run into town tomorrow, and will hit up the public wifi and see about installing vs community ed.  I'll let you know if I get it running.

Anyhow, thanks for creating this.  Looks really cool. Cant wait to try it out in a gui.
Thanks
Russ

P.S.
any thoughts off adding this to hacktoberfest?  Completely understand if you didn't want to.  I know that can create a lot of work for you with all the PR Spam.  But who knows, maybe...... (trying to be hopeful)

**Comment by LukeEmmet** [comment]
Yes it should compile in VS community edition, which is what I'm using.

Given all the controversy about Hacktoberfest this year, I won't be participating. If you or anyone wants to contribute code to GemiNaut, I will look at each PR on its merits. Thanks for your interest.

**Comment by LukeEmmet** [comment]
I've just released version 0.8.8, which includes a signed binary and installer. This should reduce the number of warnings and false positives from anti-virus utilities. 

Download the new installer from the project website here: https://www.marmaladefoo.com/pages/geminaut

Let me know if it works for you.

thanks

**Comment by Cycloneblaze** [comment]
The main gemini executable works just fine now! I did get a false positive on a gopher part of the application, though.

![image](https://user-images.githubusercontent.com/47695299/95328895-71192a00-08a6-11eb-8f94-ee06658dc327.png)

**Comment by Dr-WaSaBi** [comment]
As a complete side note 📝. @LukeEmmet you where so correct. Managed to get into town and get VS community down loaded, forked the code, cloned, and build ran and worked on the first try.  Kudos.  Now maybe I can try to help.  Haven't used VS in eons, or at least since my visual basic days 😲... so this should be fun.

**Comment by LukeEmmet** [comment]
> 
> 
> The main gemini executable works just fine now! I did get a false positive on a gopher part of the application, though.
> 
> ![image](https://user-images.githubusercontent.com/47695299/95328895-71192a00-08a6-11eb-8f94-ee06658dc327.png)

Hi @Cycloneblaze - it looks like you are still running version 0.8.7. v0.8.8 has signed binaries, including the gopher-get binary. Can you try that some time and let me know if you are still getting problem reports. Thanks

**Comment by Cycloneblaze** [comment]
Hey,

I was using 0.8.8 in fact, I had just installed it which is why I was
checking for anything like this. But I missed that was from the 0.8.7
version, they're still in the same folder on my PC.
I'd say that there are no problems with the 0.8.8, I never got any warnings
about those executables.

**Comment by LukeEmmet** [comment]
Hi @Cycloneblaze. Thanks for letting me know - so far these latest binaries seem to be generating far fewer warnings now they are signed. Cheers.

**Comment by ffuentese** [comment]
Google Chrome and Bing don't even dare to finish GemiNaut's download. It's 0.8.8 version.

**Comment by dev-kittens** [comment]
Yep - I have the same issue trying to download 0.8.8.

**Comment by LukeEmmet** [comment]
Sorry to hear some folk are still having problems getting it installed. I'm not sure what much more can be done beyond signing the binaries (which is in place since 0.8.8). Maybe GemiNaut can be submitted to the various anti-virus providers to whitelist it? 

Otherwise, feel free to download the source and build the binary yourself.

Any suggestions welcome.

**Comment by makeworld-the-better-one** [comment]
[Here](https://www.virustotal.com/gui/file/44f0126bc866c32471fc2955f79bdb00808239aaf761f3a8e570e046eb65d7f0/detection) are the VirusTotal results for the GemiNaut 0.8.8 MSI file.

![image](https://user-images.githubusercontent.com/25111343/99688314-a55e3980-2a53-11eb-8817-fd424f60aecf.png)


4 out of 51 engines detect the file, most notably Avast and it's subsidiary AVG. Not sure what Google Chrome and others are using to detect malware but it must be something similar.

Two engines flag it as generic malware, and the other two flag it as a Trojan. Not sure why.

VirusTotal confirms (on the Details page) that it is a signed file, with a valid signature. I'm not sure why some of these antiviruses are complaining. I suspect most people won't have trouble with their antiviruses (seeing as most are fine with it), but it's the Chrome downloading that is the real issue. Perhaps there is a better way to address that, like some form Google has or something.

Perhaps the issue is the bundled files? Results for those can be see on the [Relations page](https://www.virustotal.com/gui/file/44f0126bc866c32471fc2955f79bdb00808239aaf761f3a8e570e046eb65d7f0/relations). It scans each bundled file with the antiviruses as well.

![image](https://user-images.githubusercontent.com/25111343/99688271-9a0b0e00-2a53-11eb-96d3-e0ad66039028.png)

It's not so strange to me that some of the unsigned EXE's get triggered. But are the four triggered antiviruses (and Chrome) really unbundling the MSI and scanning each of the bundled files? I'm not sure.

**Comment by makeworld-the-better-one** [comment]
[Here](https://www.virustotal.com/gui/file/5a6d88f8be8a15fb6a85b5862400247b937ed98f255f80bc7f5ab369c440f1fe/detection) are the results for just gopher-get.exe. It's much worse, at 12/71 engines detecting.

![image](https://user-images.githubusercontent.com/25111343/99688981-65e41d00-2a54-11eb-8651-7f68d872923e.png)

I don't understand at all why this is flagged as a Trojan, seeing as its signed and does not do anything suspicious in terms of DLL access, etc.

---

My suggestion would be to attempt to remove EXE's from the build entirely, as I think antiviruses are seeing bundled EXE's and thinking that this must be a trojan. I'm not sure how you would do that with the existing setup though, seeing as these binaries are from entirely different language.

**Comment by johanbove** [comment]
Probably related: I got this warning after opening a Gopher link in Windows 10 in the latest Geminaut program:

>Detected: Ransom:Win32/ScarletFlash.A
> in file: C:\Program Files (x86)\MarmaladeFoo software\GemiNaut\GopherGet\gopher-get.exe

**Comment by LukeEmmet** [comment]
thanks for reporting this @johanbove. It does seem that the gopher-get exe is the one that is triggering a lot of the problems. I think I shall remove it from the next build.  Perhaps it will be better to use a native gopher client inside GemiNaut, although I wonder if the mere accessing of port 70 is considered by the AV utils to be suspect.

**Comment by LukeEmmet** [comment]
This should be much improved - the forthcoming release uses an internal protocol handler for gopher (and gemini too for that matter as they are quite similar). So these false positive virus detections should reduce. At least there will be no more use of gopher-get

**Comment by LukeEmmet** [comment]
I just submitted the new 0.8.9 candidate release to virus total - much better now, down to 2 out of 61. So it seems removing the gophe-get and gemget and using native client has helped considerably.

![virus_total_geminaut089](https://user-images.githubusercontent.com/6898220/102150343-416b3d00-3e68-11eb-9f46-7f8f9b57c7a8.png)

**Comment by LukeEmmet** [comment]
not sure how to remove that last one, but much less concerning yay!

**Comment by makeworld-the-better-one** [comment]
That's great! Although I worry if "Microsoft" means the general antivirus that comes with Windows. That would be an issue, might want to look into that.
